alias log_mysql_err="tail -f /var/log/mysql/error.log"
alias log_mysql="tail -f /var/log/mysql.log"
alias log_app="tail -f /vagrant/data/logs/app.log"
alias ls="ls -lha --color=auto"
alias runserver="python manage.py runserver 0.0.0.0:8000"